- Assets/Scripts/Player Character Movement.cs
> added documentation to script file

- Assets/InputSystem_Actions.inputactions
- Assets/Scenes/World.unity
- Assets/Scripts/Flying Vehicle.cs
- Assets/Scripts/Flying Vehicle.cs.meta
- Assets/Scripts/Input Event Dispatcher.cs
- Assets/Scripts/Interactable.cs
- Assets/Scripts/Interactable.cs.meta
- Assets/Scripts/Player Character Movement.cs
- Assets/Scripts/Sync Transform.cs
- Assets/Scripts/Sync Transform.cs.meta
- Assets/Settings/DefaultVolumeProfile.asset
- Packages/packages-lock.json
- ProjectSettings/InputManager.asset
- ProjectSettings/TagManager.asset
Closes #5 
Implementation specifics:
- Script `Flying Ship.cs` contains the actual flight controls.
- Edited `Input Event Dispatcher.cs` to maintain a notion of variable input focus. If no object explicitly has input focus, the player character has it implicitly.
- Edited `Player Character Movement.cs` to account for new notion of input focus, and also to implement an interact input button that dispatches an interact event to any `Interactable` directly in front of the player character.
- Script `Interactable.cs` identifies objects as interactable and provides an event for itself and/or other objects to listen for when that object is interacted with.
- Script `Sync Transform.cs` causes a target object's transform to behave approximately as though the `SyncTransform` object were the target …
> Implement ship flight controls.

- Assets/Scenes/Test World.unity
- Assets/Scripts/Flying Vehicle.cs
- Assets/Scripts/Sync Transform.cs
> Rotate rudder when operating ship.

- Assets/Plugins/RealtimeCSG/Editor/External/RealtimeCSG[1_559].bundle.meta
- Assets/Scenes/Test World.unity
- Assets/Scripts/Flying Ship System/Sync Transform.cs
- Assets/Scripts/Input Focus Controllers/Flying Vehicle.cs
- Assets/Scripts/Interaction/Door.cs
- Assets/Scripts/Interaction/Door.cs.meta
Closes #29 . Would also close a few other issues that I had never opened because I had not noticed them before:
- Fixes (sort of) joint-attached rigidbody children of a sync-transform target being offset from their intended positions on the target. Despite my best efforts, I wasn't able to fix this in code, so I instead fixed it by repositioning the ship geometry with respect to the physics controller so that the offset would be zero.
- Fixes the rudder eventually beginning to turn the wrong way if the ship gets turned around enough.
- Fixes (I think) weird unpredictable behavior of FlyingVehicle's config properties.
> Make ship doors openable and fix various small bugs in ship physics.

- Assets/Prefabs/Interaction/Command Block.prefab.meta
> Fix wrong GUID on Command Block.prefab.meta

- Assets/Prefabs/Core.meta
- Assets/Prefabs/Core/Scene Core (Player, GameManager, Main Lights).prefab
- Assets/Prefabs/Core/Scene Core (Player, GameManager, Main Lights).prefab.meta
- Assets/Prefabs/Core/Ship.prefab
- Assets/Prefabs/Core/Ship.prefab.meta
- Assets/Scenes/Test World.unity
> Turn scene core and ship into prefabs

- Assets/Scripts/Flying Ship System/Sync Transform.cs
> Fix SyncTransform for rigidbodies

- Assets/Imported Assets/3D Birds Prototype Pack/Materials/GrassMaterial.mat
- Assets/Imported Assets/BrokenVector/LowPolyDungeon/Materials/FakeSky.mat
- Assets/Imported Assets/WoodsLifestyle/Models/Vegetation/Bushes/Materials/Leafs_Green_02.mat
- Assets/Imported Assets/WoodsLifestyle/Models/Vegetation/Flowers/Materials/Stem_Green_01.mat
- Assets/Imported Assets/WoodsLifestyle/Models/Vegetation/Grass/Materials/Grass_Green_01.mat
- Assets/Imported Assets/WoodsLifestyle/Models/Vegetation/Mushrooms/Materials/Head_Red_01.mat
- Assets/Imported Assets/WoodsLifestyle/Models/Vegetation/Mushrooms/Materials/StemRing_Blue_01.mat
- Assets/Imported Assets/WoodsLifestyle/Models/Vegetation/Mushrooms/Materials/Stem_Brown_01.mat
- Assets/Imported Assets/WoodsLifestyle/Models/Vegetation/Mushrooms/Materials/Stem_White_01.mat
- Assets/Scenes/Procgen World Test.unity
- Assets/Scenes/Procgen World Test.unity.meta
- Assets/Scripts/Procedural Generation.meta
- Assets/Scripts/Procedural Generation/WorldGenerator.cs
- Assets/Scripts/Procedural Generation/WorldGenerator.cs.meta
- Assets/Scripts/Procedural Generation/WorldGeneratorNode.cs
- Assets/Scripts/Procedural Generation/WorldGeneratorNode.cs.meta
- Assets/Scripts/Utility/ExceptionAbout.cs
- Assets/Scripts/Utility/ExceptionAbout.cs.meta
> Implement a worldgen algorithm

- Assets/Scenes/Test World.unity
- Assets/Scripts/Controllers/Flying Vehicle.cs
> Fix ship jitter

- Assets/Prefabs/Core/Ship.prefab
> Reduce ship traction

- Assets/Prefabs/Core/Ship.prefab
- Assets/Scripts/Controllers/Flying Vehicle.cs
- Assets/Settings/PC_RPAsset.asset
> Implement altitude controls for flying ship

- Assets/Settings/PC_RPAsset.asset
> Reenable HDR on PC_RPAsset

- Assets/Scripts/Audio Scripts/FootstepSound.cs
- Assets/Scripts/Controllers/Player Character Controller.cs
> Fix spurious footsteps while aboard moving objects

- Assets/Prefabs/Core/Ship.prefab
- Assets/Scripts/Audio Scripts/FootstepSound.cs
- Assets/Scripts/Controllers/Player Character Controller.cs
- Assets/Scripts/Props.meta
- Assets/Scripts/Props/Ladder.cs
- Assets/Scripts/Props/Ladder.cs.meta
> Implement climbing ladders

- Assets/Scripts/Controllers/Flying Vehicle.cs
> Fix player slant when dismounting ship

- Assets/Audio/Music/sailing music 2.mp3.meta
- Assets/Audio/Music/sailing music.wav.meta
Adding Sailing Music, two options
> Adding Sailing Music

- Assets/Prefabs/Core/Ship.prefab
- Assets/Scripts/Controllers/Flying Vehicle.cs
> Implement ship braking without anchor

- Assets/Prefabs/Core/Scene Core (Player, GameManager, Main Lights).prefab
> Fix canvas not scaling with window size

- Assets/Prefabs/Core/Ship.prefab
- Assets/Scripts/Controllers/Player Character Controller.cs
- Assets/Scripts/Flying Ship System/Anchor Control.cs
- Assets/Scripts/Flying Ship System/Anchor Control.cs.meta
- Assets/Scripts/Props/Rope.cs
- Assets/Scripts/Props/Rope.cs.meta
> Feat ship anchor

- Assets/Imported Assets/UnityTechnologies/ParticlePack/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
- Assets/Prefabs/UI/ControlsMenu.prefab
- Assets/Prefabs/UI/ControlsMenu.prefab.meta
- Assets/Prefabs/UI/ControlsMenuEntry.prefab
- Assets/Prefabs/UI/ControlsMenuEntry.prefab.meta
- Assets/Prefabs/UI/MainMenu.prefab
- Assets/Scripts/UI/ControlsMenu.cs
- Assets/Scripts/UI/ControlsMenu.cs.meta
- Assets/Scripts/UI/ControlsMenuEntry.cs
- Assets/Scripts/UI/ControlsMenuEntry.cs.meta
- Assets/Scripts/UI/MainMenu.cs
- Assets/UI Toolkit.meta
- Assets/UI Toolkit/PanelSettings.asset
- Assets/UI Toolkit/PanelSettings.asset.meta
- Assets/UI Toolkit/UnityThemes.meta
- Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss
- Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss.meta
Closes #273
Closes #274
Closes #276
> Fully implement controls rebind menu

- Assets/Scripts/Audio Scripts/Sound Types/ZoneSound.cs
> allow baseline for controlling music volume

- Assets/Accessibility/ButtonPrompts/InputSystem_Actions.cs
- Assets/Accessibility/ButtonPrompts/InputSystem_Actions.inputactions
- Assets/Scripts/Controllers/Flying Vehicle.cs
> Fix ship camera

- Assets/Accessibility/ButtonPrompts/InputSystem_Actions.cs
- Assets/Accessibility/ButtonPrompts/InputSystem_Actions.inputactions
- Assets/Prefabs/Core/Scene Core (Player, GameManager, Main Lights).prefab
- Assets/Scripts/Controllers/Flying Vehicle.cs
- Assets/Scripts/Controllers/InputModeManager.cs
- Assets/Scripts/UI/ControlsMenu.cs
- Assets/Scripts/UI/MainMenu.cs
- Assets/Scripts/UI/UIStack.cs
- Assets/Scripts/UI/UIStack.cs.meta
- Assets/Scripts/Utility/SceneCore.cs
> Feat stack based UI

- Assets/Prefabs/Core/Scene Core (Player, GameManager, Main Lights).prefab
- Assets/Scripts/Persistent Data.meta
- Assets/Scripts/Persistent Data/ControlRebindPrefs.cs
- Assets/Scripts/Persistent Data/ControlRebindPrefs.cs.meta
- Assets/Scripts/UI/ControlsMenu.cs
> Persist control rebinds between play sessions

- Assets/Prefabs/Core/Scene Core (Player, GameManager, Main Lights).prefab
- Assets/Scripts/Persistent Data/FullScreenPref.cs
- Assets/Scripts/Persistent Data/FullScreenPref.cs.meta
- Assets/Scripts/UI/MainMenu.cs
- ProjectSettings/ProjectSettings.asset
> Implement fullscreen toggle

- Assets/Scripts/Audio Scripts/FadeAudioSource.cs
- Assets/Scripts/Audio Scripts/Sound Types/ZoneSound.cs
> Fix music playing when muted

- Assets/Prefabs/Core/Ship.prefab
> Increase ship acceleration

- Assets/Prefabs/Core/Ship.prefab
> Fix sailing music not stopping

- Assets/Prefabs/UI/ControlsMenu.prefab
- Assets/Prefabs/UI/ControlsMenuEntry.prefab
- Assets/Prefabs/UI/MainMenu.prefab
- Assets/Scripts/UI/ControlsMenu.cs
- Assets/Scripts/UI/ControlsMenuEntry.cs
- Assets/Scripts/UI/MainMenu.cs
- Assets/Scripts/UI/ScrollbarFollowSelect.cs
- Assets/Scripts/UI/ScrollbarFollowSelect.cs.meta
- Assets/Scripts/UI/UIStack.cs
> Allow navigating menus using keybinds

- Assets/Prefabs/Core/Scene Core (Player, GameManager, Main Lights).prefab
- Assets/Scripts/Controllers/Flying Vehicle.cs
- Assets/Scripts/Controllers/Player Character Controller.cs
- Assets/Scripts/Persistent Data/LookSensPrefs.cs
- Assets/Scripts/Persistent Data/LookSensPrefs.cs.meta
- Assets/Scripts/UI/ControlsMenu.cs
> Implement look sensitivity preferences

- Assets/Accessibility/ButtonPrompts/InputSystem_Actions.cs
- Assets/Accessibility/ButtonPrompts/InputSystem_Actions.inputactions
- Assets/Prefabs/UI/ControlsMenu.prefab
- Assets/Prefabs/UI/ControlsMenuEntry.prefab
- Assets/Scripts/UI/ControlsMenu.cs
> Show device type in controls rebind menu

- Assets/Prefabs/UI/ConfirmQuitMenu.prefab
- Assets/Prefabs/UI/ConfirmQuitMenu.prefab.meta
- Assets/Prefabs/UI/MainMenu.prefab
- Assets/Scripts/UI/ConfirmQuitMenu.cs
- Assets/Scripts/UI/ConfirmQuitMenu.cs.meta
- Assets/Scripts/UI/ControlsMenu.cs
- Assets/Scripts/UI/MainMenu.cs
- Assets/Scripts/UI/UIStack.cs
- Assets/Scripts/Utility/Misc.cs
> Implement quit button

- Assets/Prefabs/Core/Scene Core (Player, GameManager, Main Lights).prefab
- Assets/Scripts/Persistent Data/ProgressPref.cs
- Assets/Scripts/Persistent Data/ProgressPref.cs.meta
- Assets/Scripts/Story Scripts/StoryManager.cs
- Assets/Scripts/UI/ConfirmQuitMenu.cs
> Implement saving and loading progress

- Assets/Prefabs/Core/Scene Core (Player, GameManager, Main Lights).prefab
- Assets/Scripts/Persistent Data/HighContrastPref.cs
- Assets/Scripts/Persistent Data/HighContrastPref.cs.meta
- Assets/Scripts/UI/MainMenu.cs
- Assets/Settings/VolumeProfile_HighContrast_Indoors.asset
- Assets/Settings/VolumeProfile_HighContrast_Indoors.asset.meta
- Assets/Settings/VolumeProfile_HighContrast_Outdoors.asset
- Assets/Settings/VolumeProfile_HighContrast_Outdoors.asset.meta
> Implement high-contrast mode

- Assets/Prefabs/UI/ConfirmQuitMenu.prefab
> Fix select highlighting and navigation on quit menu

- Assets/Scripts/Audio Scripts/Sound Types/ZoneSound.cs
> Fix ambient noise not playing

- Assets/Prefabs/Enemies/test cannon.prefab
- Assets/Scripts/Enemies/AI/TestCannonAI.cs
- Assets/Scripts/Enemies/Control Interfaces/Projectile Launcher.cs
> Make ProjectileLauncher.Aim() behave more intuitively

- Assets/Scenes/Cannon Test Scene.unity
- Assets/Scripts/Controllers/Flying Vehicle.cs
> Fix ship acting like RC car

- Assets/Prefabs/Core/Ship.prefab
- Assets/Scenes/Cannon Test Scene.unity
- Assets/Scripts/Enemies/AI/TestCannonAI.cs
- Assets/Scripts/Flying Ship System/Player Ship.cs
- Assets/Scripts/Flying Ship System/Player Ship.cs.meta
- Assets/Scripts/Utility/SceneCore.cs
> Improve cannon AI

- Assets/Prefabs/Effects.meta
- Assets/Prefabs/Effects/Cannonball Explosion.prefab
- Assets/Prefabs/Effects/Cannonball Explosion.prefab.meta
- Assets/Prefabs/Enemies/test cannonball.prefab
Closes #448 
Object still needs audio
> Create explosion when cannonball is destroyed

- Assets/Scripts/Player/Controllers/Flying Vehicle.cs
- Assets/Scripts/Player/Inventory System/Inventory.cs
Use new public methods in Inventory class HideEquippedItem() and ShowEquippedItem() to hide current equipped weapon and re-show it.
> fixed item showing up while controlling ship

- Assets/Scenes/Cannon Test Scene.unity
- Assets/Scripts/Enemies/AI/TestCannonAI.cs
- Assets/Scripts/Enemies/Animation Controllers/TestCannonAnimator.cs
- Assets/Scripts/Enemies/Control Interfaces/Projectile Launcher.cs
- Assets/Scripts/Utility/Misc.cs
> Fix projectile launcher implementation

- Assets/Prefabs/Core/Ship.prefab
- Assets/Prefabs/Props/Destructible Wall Circular.prefab
- Assets/Prefabs/Props/Destructible Wall Circular.prefab.meta
- Assets/Scenes/Cannon Test Scene.unity
- Assets/Scripts/Enemies/Control Interfaces/Projectile Launcher.cs
- Assets/Scripts/Player/Controllers/Player Ship Cannon.cs
- Assets/Scripts/Player/Controllers/Player Ship Cannon.cs.meta
- Assets/Scripts/Props/Destructible Mesh Piece.cs
- Assets/Scripts/Utility/Misc.cs
> Implement destructible walls and player cannons

- Assets/Imported Assets/BrokenVector/LowPolyBrickHouses/Prefabs/Bench.prefab
- Assets/Imported Assets/BrokenVector/LowPolyBrickHouses/Prefabs/Birchtree.prefab
- Assets/Imported Assets/BrokenVector/LowPolyBrickHouses/Prefabs/Chair.prefab
- Assets/Imported Assets/BrokenVector/LowPolyBrickHouses/Prefabs/RiverWall.prefab
- Assets/Imported Assets/BrokenVector/LowPolyBrickHouses/Prefabs/RiverWallOpen.prefab
- Assets/Imported Assets/BrokenVector/LowPolyBrickHouses/Prefabs/RiverWallStairs.prefab
- Assets/Imported Assets/Daniel Mistage/Stylized Fantasy Armory/Prefabs/Decorative Props/Fences/Fence.001.prefab
- Assets/Imported Assets/Daniel Mistage/Stylized Fantasy Armory/Prefabs/Decorative Props/Fences/Fence.002.prefab
- Assets/Imported Assets/Daniel Mistage/Stylized Fantasy Armory/Prefabs/Decorative Props/Fences/Fence.003.prefab
- Assets/Imported Assets/FantasyMedievalTown_LITE/Prefabs/Barrel_01_LITE.prefab
- Assets/Imported Assets/Fries and Seagull/Bar 02/Prefabs/Tables & Chairs/Bar Stool.prefab
- Assets/Scripts/Level/OnGameStart.cs
fixed some tags on townsport
tagged all of cicadia
> Tagged Cicadia, Fixed Tags on Townsport
